#Database
spring:
  application:
    name: rabbitbank
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rabbitbank
    username: postgres
    password: postgres
    initialization-mode: always
  api:
    version: 1.0.0
#JPA properties
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

rabbitbank:
  jwt:
    expiration: 86400000
    secretString: 8pK_Lp/~J<0UBzIH({0}CBPTAQAQ0u]sA|D"eB><V{ZoWyZhBE+-ygn|@EZhJ_=}@ygp;H%T9M3SlKq&};-Tp"_pJ/}%[jLIzxTi/5]fGm%Y@;U>Z+"/(9v@D/`XUJv-4TaZw^bs/n?MfFRYs%WtFKq&};-Tp"@,*UtH!Rm9>{xD_+:*7U9o)_@^H$l9N%I~O^rl:j8jo!-HbpmLQt)x
