#Database
spring:
  application:
    name: rabbitbank
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rabbitbank
    username: postgres
    password: 242400Op@!!@@
    initialization-mode: always
  api:
    version: 1.0.0
#JPA properties
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
